### ISSUE TITLE
[UnionDHT] ESET found Threat

### ISSUE THREAD

**Issue by Obegg** [msagca/qbittorrent_plugins#1]
![Capture](https://user-images.githubusercontent.com/13978119/155092566-91f17649-7020-4759-b262-98c0d141c194.PNG)

Using `#VERSION: 1.1`

**Comment by msagca** [comment]
Hi @Obegg  
This is directly related to the website/webpage contents. There is some information [here](https://www.enigmasoftware.com/htmlscrinjectbgen-removal/) about this threat. However, I wouldn't worry about this since the search plugin does not run any JavaScript code found on the website, it just parses the HTML file.

**Comment by msagca** [comment]
Hi @Obegg
This is directly related to the website/webpage contents. I wouldn't worry about this since the [html.parser](https://docs.python.org/3/library/html.parser.html) module that I'm using in the plugin does not execute any HTML script, it simply parses HTML text.
